#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

quarkus.index-dependency.rimfrost-framework-process.group-id=se.fk.rimfrost.framework.process
quarkus.index-dependency.rimfrost-framework-process.artifact-id=rimfrost-framework-process

# Container image configuration
quarkus.container-image.build=true
#TODO Change quarkus.container-image.name
quarkus.container-image.name=rimfrost-template-process
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false

#TODO Specify the incoming request topic
mp.messaging.incoming.template-handlaggning-requests.connector=smallrye-kafka
mp.messaging.incoming.template-handlaggning-requests.auto.offset.reset=earliest
mp.messaging.incoming.template-handlaggning-requests.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

#TODO Specify the outgoing response topic
mp.messaging.outgoing.template-handlaggning-responses.connector=smallrye-kafka
mp.messaging.outgoing.template-handlaggning-responses.value.serializer=org.apache.kafka.common.serialization.StringSerializer

kogito.quarkus.events.threads.queueSize=10
kogito.messaging.as-cloudevents=true
quarkus.kogito.devservices.enabled=false