name: Smoke Integration Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration-tests:
    name: Run Smoke Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      GITHUB_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up JDK 21
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # --- Run integration tests ---
      - name: Run Maven verify
        run: ./mvnw -s settings.xml verify
